# Generated by Django 3.2 on 2022-07-06 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateField(auto_now_add=True, verbose_name='created at'),
        ),
    ]
